import { useState } from 'react';
import AddressSearchField from './AddressSearchField.jsx';

function initFrom(p) {
  return {
    name: p?.name ?? '',
    category_id: p?.category_id ?? '',
    address: p?.address ?? '',
    city: p?.city ?? null,
    latitude: p?.latitude ?? null,
    longitude: p?.longitude ?? null,
    url: p?.url ?? '',
    notes: p?.notes ?? '',
    estimated_duration_minutes:
      p?.estimated_duration_minutes != null ? String(p.estimated_duration_minutes) : '',
  };
}

export default function PoiForm({ initial, categories, onSubmit, onCancel }) {
  const [form, setForm] = useState(initFrom(initial));
  const [error, setError] = useState(null);
  const [saving, setSaving] = useState(false);

  const linked = !!initial?.accommodation_id; // generated by an accommodation
  const set = (k) => (e) => setForm((f) => ({ ...f, [k]: e.target.value }));

  const resolved = form.latitude != null && form.longitude != null;

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(null);

    if (!form.name.trim()) return setError('Falta el nombre.');
    if (!form.category_id) return setError('Elegí una categoría.');
    if (!resolved) return setError('Buscá una dirección y elegí un resultado de la lista.');
    if (form.estimated_duration_minutes !== '' && (!Number.isInteger(Number(form.estimated_duration_minutes)) || Number(form.estimated_duration_minutes) <= 0)) {
      return setError('La duración estimada debe ser un número entero de minutos mayor a 0.');
    }

    const payload = {
      name: form.name.trim(),
      category_id: form.category_id,
      address: form.address,
      city: form.city,
      latitude: form.latitude,
      longitude: form.longitude,
      url: form.url.trim() || null,
      notes: form.notes.trim() || null,
      estimated_duration_minutes:
        form.estimated_duration_minutes === '' ? null : Number(form.estimated_duration_minutes),
    };

    setSaving(true);
    try {
      await onSubmit(payload);
    } catch (err) {
      setError(err.message);
      setSaving(false);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      {error && <div className="alert alert-error">{error}</div>}

      {linked && (
        <p className="muted" style={{ marginTop: 0 }}>
          🏨 Generado por el alojamiento. El nombre y la ubicación se sincronizan
          desde el alojamiento; acá solo podés editar notas y enlace.
        </p>
      )}

      <div className="field">
        <label htmlFor="poi-name">Nombre *</label>
        <input
          id="poi-name"
          value={form.name}
          onChange={set('name')}
          disabled={linked}
          placeholder="Templo Kiyomizu-dera"
        />
      </div>

      <div className="field">
        <label htmlFor="poi-cat">Categoría *</label>
        <select id="poi-cat" value={form.category_id} onChange={set('category_id')} disabled={linked}>
          <option value="">Elegí una…</option>
          {categories.map((c) => (
            <option key={c.id} value={c.id}>
              {c.name}
            </option>
          ))}
        </select>
      </div>

      <AddressSearchField
        id="poi-addr"
        label="Dirección * (buscá y elegí un resultado)"
        initialAddress={initial?.address ?? ''}
        disabled={linked}
        onResolve={({ address, latitude, longitude, city }) =>
          setForm((f) => ({ ...f, address, latitude, longitude, city }))
        }
        onInvalidate={(text) =>
          setForm((f) => ({ ...f, address: text, latitude: null, longitude: null, city: null }))
        }
      />
      {resolved && (
        <div className="muted poi-search-hint" style={{ marginTop: '-0.4rem', marginBottom: '0.9rem' }}>
          📍 {Number(form.latitude).toFixed(5)}, {Number(form.longitude).toFixed(5)} — ubicación resuelta
          {form.city && <> · Ciudad: {form.city}</>}
        </div>
      )}

      <div className="field">
        <label htmlFor="poi-url">Enlace</label>
        <input id="poi-url" type="url" value={form.url} onChange={set('url')} placeholder="https://…" />
      </div>

      <div className="field">
        <label htmlFor="poi-dur">Duración estimada de visita (min)</label>
        <input
          id="poi-dur"
          type="number"
          min="1"
          step="1"
          value={form.estimated_duration_minutes}
          onChange={set('estimated_duration_minutes')}
          placeholder="90"
        />
      </div>

      <div className="field">
        <label htmlFor="poi-notes">Notas</label>
        <textarea id="poi-notes" rows={3} value={form.notes} onChange={set('notes')} />
      </div>

      <div className="row-between" style={{ marginTop: '1.25rem', justifyContent: 'flex-end' }}>
        <button type="button" className="btn btn-secondary" onClick={onCancel} disabled={saving}>
          Cancelar
        </button>
        <button type="submit" className="btn" disabled={saving}>
          {saving ? 'Guardando…' : 'Guardar'}
        </button>
      </div>
    </form>
  );
}
